In [1]:
import boto3
import pandas as pd

In [2]:
#criar client s3 para manipular o bucket s3
s3_client = boto3.client('s3')

realizando download de arquivo em bucket utilizando API do aws s3

In [5]:
s3_client.download_file('caio-dev-edc','base_dacred_trat.csv','base_dacred_trat_down.csv')
customers_df = pd.read_csv('base_dacred_trat_down.csv')

customers_df

,Data,vendedor_codigo,Nome,CPF,Nª Telefone,numero_estado,Data Nasc,NUMERO_BANCO,Valor venda,Tratativa
0,09.6.2021,2,DAVID MIRANDA DA SILVA JUNIOR,32578625808,11985183580,24.0,24.10.1975,1.0,3575.06,1.0
1,09.6.2021,2,NEIDE FATIMA FRANCISCO AMORIM,6530217800,11 958539553,24.0,29.5.1978,1.0,6355.61,1.0
2,09.6.2021,2,ELIZAMA DA SILVA DIAS,40856239828,11949137692,24.0,26.4.1974,1.0,2087.97,1.0
3,10.6.2021,2,INGRID COSTA DE ALBUQUERQUE,46284926898,11 95225-7168,24.0,07.6.1963,1.0,1538.65,1.0
4,10.6.2021,2,CRISTIANE SOUZA DA SILVA,22677766850,NaN,15.0,27.5.1980,1.0,1913.08,1.0
...,...,...,...,...,...,...,...,...,...,...
946,27.10.2021,3,GRAZIELA DE OLIVEIRA SANTOS,12643501632,3592711079,22.0,16.3.1978,2.0,1496.94,2.0
947,27.10.2021,5,Eliziene bacelar de Lima Barbosa,94670455168,6791532170,4.0,22.9.1962,1.0,1545.20,1.0
948,27.10.2021,13,Andreson Cardoso dos Santos,1921132590,7598949676,6.0,20.4.1950,5.0,285.88,1.0
949,27.10.2021,3,GLEICIANE DA GAMA GONCALVES,2559270293,92995291483,16.0,18.7.1983,5.0,1994.32,1.0
950,27.10.2021,3,William Castro Santos,3442804388,6191101461,1.0,30.10.1968,1.0,743.01,2.0

realizando upload de arquivo em bucket utilizando API do aws s3

In [ ]:
s3.client.upload_file